-- 07_comparisons.sql — Annex H, dimension-keyed
-- dimensions: price, commute, schools, amenities, maturity

insert into comparisons (
  community_id, dimension, valley_advantage, other_advantage, honest_read,
  confidence, source_id, sort_order
)
select c.id, v.dimension, v.valley_advantage, v.other_advantage, v.honest_read,
       'corroborated'::confidence_level, 'a1000000-0000-4000-8000-000000000001'::uuid, v.sort_order
from communities c
join (values
  -- Arabian Ranches 3
  ('arabian-ranches-3', 'price',
   'Materially cheaper registered rents (~AED 146,571 vs AR3 villa ~AED 194,889 directional).',
   'Higher price band buys commute time and maturity.',
   'AR3 averages ~AED 194,889 new-contract villa rent vs The Valley''s registered ~AED 146,571 — roughly AED 48,000/yr, mostly buying commute time and maturity. DIFC commuter → AR3. Remote, Silicon Oasis or Academic City → The Valley. (AR3 figure is Property Finder listing data, not like-for-like with DLD. Directional only.)',
   10),
  ('arabian-ranches-3', 'commute',
   'Better fit for Silicon Oasis / Academic City oriented households.',
   'Shorter commute to Downtown/DIFC.',
   'DIFC commuter → AR3. Remote, Silicon Oasis or Academic City → The Valley.',
   20),
  ('arabian-ranches-3', 'schools',
   null,
   'Schools inside and adjacent (JESS, Ranches Primary).',
   'AR3 wins on in-community and adjacent school density; The Valley has no school inside the gates.',
   30),
  ('arabian-ranches-3', 'amenities',
   'Golden Beach has no AR3 equivalent. In-community medical centre, two pharmacies, nursery and grocery already trading. Larger, lower-density master plan.',
   '30,000 sqm Central Park. Mature brand.',
   'Amenity programme differs in kind: AR3 is settled park + schools; The Valley sells beach lagoon + town-centre programme that is still partly specified rather than verified open.',
   40),
  ('arabian-ranches-3', 'maturity',
   'In-community services already trading (clinic, pharmacies, nursery, grocery).',
   'Settled tenant base and mature brand.',
   'AR3 is the more settled community today; The Valley is earlier in the delivery curve outside Eden, Nara and Talia.',
   50),

  -- Villanova
  ('villanova', 'price',
   null,
   'Cheaper.',
   'Villanova is the pragmatist''s choice and cheaper. The Valley asks a premium for Emaar plus amenities that are partly still being built — defensible only once amenity status is verified.',
   10),
  ('villanova', 'commute',
   null,
   'Closer to Academic City and Silicon Oasis.',
   'Villanova is closer to Academic City and Silicon Oasis; The Valley sits further out on the E66.',
   20),
  ('villanova', 'schools',
   null,
   'GEMS school inside the community.',
   'Villanova has an in-community GEMS school; The Valley has none.',
   30),
  ('villanova', 'amenities',
   'Far superior amenity programme. Larger units. Newer stock. Emaar brand and build quality.',
   'Fully delivered, no construction-zone problem.',
   'The Valley''s amenity premium is only defensible once amenity operational status is verified.',
   40),
  ('villanova', 'maturity',
   'Newer stock.',
   'Fully delivered, no construction-zone problem.',
   'Villanova is finished; The Valley still has active delivery beyond the first three clusters.',
   50),

  -- Town Square Dubai
  ('town-square-dubai', 'price',
   null,
   'Cheaper entry.',
   'Town Square wins on price and on being finished. The Valley''s counter is space and product tier.',
   10),
  ('town-square-dubai', 'commute',
   null,
   null,
   'Both sit outside the core; neither is a Downtown convenience play.',
   20),
  ('town-square-dubai', 'schools',
   null,
   null,
   'Neither matches AR3 for in-community school density.',
   30),
  ('town-square-dubai', 'amenities',
   'Much larger homes. Lower density. Villa product Town Square lacks entirely.',
   'Walkable central square with real F&B density. Established retail. Medcare on site.',
   'Different tenant: Town Square for walkable finished density; The Valley for space and villa tiers (Rivana, Alana, Farm Grove, Farm Gardens).',
   40),
  ('town-square-dubai', 'maturity',
   'Emaar vs Nshama on build quality and resale liquidity.',
   'Mature and delivered.',
   'Town Square is finished; The Valley is not fully delivered.',
   50),

  -- DAMAC Hills 2
  ('damac-hills-2', 'price',
   null,
   'Lowest entry price in the corridor.',
   'Much cheaper, and for a budget-constrained family that trade is rational. Quantify the difference; don''t disparage.',
   10),
  ('damac-hills-2', 'commute',
   null,
   null,
   'Same general Dubailand / E66 corridor; price and quality dominate the comparison.',
   20),
  ('damac-hills-2', 'schools',
   null,
   null,
   'Neither has a decisive in-community school advantage documented in Doc 1 for this pair.',
   30),
  ('damac-hills-2', 'amenities',
   'Substantially better build quality and finish. Far lower density. Better landscaping. Larger plots.',
   'Large community centre with Carrefour, clinic, gym, nursery, salons and spas. Real retail density. Fully delivered.',
   'DAMAC Hills 2''s community amenities are publicly criticised by residents — the community gym holds a 2.0 rating across 44 reviews for a community of roughly 30,000. That is documented, not opinion. But it is much cheaper.',
   40),
  ('damac-hills-2', 'maturity',
   'Emaar community management. Stronger resale and rental liquidity.',
   'Fully delivered.',
   'DH2 is finished stock at a lower price; The Valley trades unfinished amenity verification for Emaar liquidity and lower density.',
   50),

  -- Tilal Al Ghaf
  ('tilal-al-ghaf', 'price',
   'Considerably cheaper. Better value per sq ft.',
   'Higher-tier finish. Stronger prestige.',
   'Different market. Useful mainly as a reference point — equivalent lifestyle at roughly double the cost.',
   10),
  ('tilal-al-ghaf', 'commute',
   null,
   'Closer to Sheikh Zayed Road.',
   'Tilal Al Ghaf is the closer SZR play; The Valley is the E66 value play.',
   20),
  ('tilal-al-ghaf', 'schools',
   null,
   null,
   'Not the primary differentiator documented for this pair in Doc 1.',
   30),
  ('tilal-al-ghaf', 'amenities',
   'Larger master plan.',
   'Lagoon Al Ghaf beats Golden Beach.',
   'Different market: lagoon prestige vs value-tier beach-lagoon master plan.',
   40),
  ('tilal-al-ghaf', 'maturity',
   'Emaar''s delivery record vs MAF''s shorter residential history.',
   'Higher-tier finish and prestige.',
   'Reference point rather than a like-for-like substitute.',
   50)
) as v(slug, dimension, valley_advantage, other_advantage, honest_read, sort_order)
  on c.slug = v.slug;
